### ISSUE TITLE
RMSE value?

### ISSUE THREAD

**Issue by Halfpoint1** [KevinJ-Huang/BMNet#4]
Could you provide the MATLAB code for evaluating RMSE? I used your nonshadow image results for evaluation, but received results that were inconsistent with the paper

**Comment by zhuyr97** [comment]
Refer to https://github.com/zhuyr97/AAAI2022_Unfolding_Network_Shadow_Removal/tree/master/codes

**Comment by zhuyr97** [comment]
> 

Although RMSE is reported in the papers, MAE is actually used as the evaluation metric by previous methods, including ours.
